# This file was generated by GoReleaser. DO NOT EDIT.
cask "invowk" do
  name "invowk"
  desc "A dynamically extensible command runner"
  homepage "https://invowk.dev"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "invowk"

  on_macos do
    on_intel do
      url "https://github.com/invowk/invowk/releases/download/v#{version}/invowk_#{version}_darwin_amd64.tar.gz"
      sha256 "b3d1ed02f5ed6c58c086c3a5ffa97f4615f7e903efc03cb4379e30d175a625e3"
    end
    on_arm do
      url "https://github.com/invowk/invowk/releases/download/v#{version}/invowk_#{version}_darwin_arm64.tar.gz"
      sha256 "c10f7484d11b3f6bc79216d06eefdd91325c69ac6cf054e460f1e01603bee7c8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/invowk/invowk/releases/download/v#{version}/invowk_#{version}_linux_amd64.tar.gz"
      sha256 "3840a17d64aa456b5ef578cac659c68868f6d5e55a367b65b102e01921a42e34"
    end
    on_arm do
      url "https://github.com/invowk/invowk/releases/download/v#{version}/invowk_#{version}_linux_arm64.tar.gz"
      sha256 "9f8f0341e5572b85597feb7347ff257a340aa46e1e5ab9c1bd6e092964f2bda2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/invowk"]
    end
  end

  # No zap stanza required
end
