# This file was generated by GoReleaser. DO NOT EDIT.
cask "invowk" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "5adb3ef4bbadeadd5d9bb4b04a4d5ead4982b5d1e1466f86ff1471d1207e9565"
      url "https://github.com/invowk/invowk/releases/download/v#{version}/invowk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ffb7aeacca1407a0e0284c842893ce7a652f5fff0ea42546c1ccd1bfb1e241bd"
      url "https://github.com/invowk/invowk/releases/download/v#{version}/invowk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "18a087de514ac3860bf2dd47df990488eef5ff3d7d398379beb41fe501f0d8d7"
      url "https://github.com/invowk/invowk/releases/download/v#{version}/invowk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8bc6f45f1ea6afc9d2cfaf6f3dd8179b8bf2fb49ef1a37c2abf177c6c0a1b980"
      url "https://github.com/invowk/invowk/releases/download/v#{version}/invowk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "invowk"
  desc "A dynamically extensible command runner"
  homepage "https://invowk.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "invowk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/invowk"]
    end
  end

  # No zap stanza required

end
