# This file was generated by GoReleaser. DO NOT EDIT.
cask "invowk" do
  name "invowk"
  desc "A dynamically extensible command runner"
  homepage "https://invowk.dev"
  version "0.7.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "invowk"

  on_macos do
    on_intel do
      url "https://github.com/invowk/invowk/releases/download/v#{version}/invowk_#{version}_darwin_amd64.tar.gz"
      sha256 "9452419c66f8fcb714bcc214ac5d836745e6f6e5a85c9128ad76b4abee371a9e"
    end
    on_arm do
      url "https://github.com/invowk/invowk/releases/download/v#{version}/invowk_#{version}_darwin_arm64.tar.gz"
      sha256 "f03a4891075e86d0c60f381cda3dacd97a4adbd69ecaeea0aa5e671965c95dc3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/invowk/invowk/releases/download/v#{version}/invowk_#{version}_linux_amd64.tar.gz"
      sha256 "b93d0eeb71dc910b34e0895ca352359d13380a3d7ab844d89d931f31d59c8b1f"
    end
    on_arm do
      url "https://github.com/invowk/invowk/releases/download/v#{version}/invowk_#{version}_linux_arm64.tar.gz"
      sha256 "1a84745ca0510bee19edc9d383d67e0c0554fb1a3bc79628f25bb758dfc95c3b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/invowk"]
    end
  end

  # No zap stanza required
end
